import { OptimizerConfig } from '../../context/types';

export const OPTIMIZER_CONFIGS: OptimizerConfig[] = [
  {
    id: 'batch',
    name: 'Batch GD',
    color: '#4444ff',
    defaultEnabled: true,
    params: [
      {
        id: 'learningRate',
        label: 'Learning Rate',
        type: 'range',
        min: 0.001,
        max: 0.1,
        step: 0.001,
        default: 0.01,
        tooltip: 'Controls the step size at each iteration. Higher values converge faster but may overshoot; lower values are more precise but slower.',
      },
      {
        id: 'useConvergence',
        label: 'Run Until Convergence',
        type: 'checkbox',
        default: true,
      },
      {
        id: 'iterations',
        label: 'Iterations',
        type: 'range',
        min: 50,
        max: 500,
        step: 10,
        default: 100,
        tooltip: 'Number of optimization steps to perform. More iterations allow the optimizer to explore further but take longer to compute.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: false,
        },
      },
      {
        id: 'maxIterations',
        label: 'Max Iterations',
        type: 'range',
        min: 500,
        max: 20000,
        step: 500,
        default: 10000,
        tooltip: 'Maximum number of iterations when using convergence mode. Acts as a safety limit to prevent infinite loops.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
      {
        id: 'convergenceThreshold',
        label: 'Convergence Threshold',
        type: 'range',
        min: 0.000001,
        max: 0.01,
        step: 0.000001,
        default: 0.0001,
        tooltip: 'Stops optimization when the gradient magnitude falls below this value, indicating we\'re near a local minimum.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
    ],
  },
  {
    id: 'momentum',
    name: 'Momentum GD',
    color: '#44ff44',
    defaultEnabled: true,
    params: [
      {
        id: 'learningRate',
        label: 'Learning Rate',
        type: 'range',
        min: 0.001,
        max: 0.1,
        step: 0.001,
        default: 0.01,
        tooltip: 'Controls the step size at each iteration. Higher values converge faster but may overshoot; lower values are more precise but slower.',
      },
      {
        id: 'momentum',
        label: 'Momentum',
        type: 'range',
        min: 0,
        max: 0.99,
        step: 0.01,
        default: 0.9,
        tooltip: 'Accumulates a fraction of the previous update direction. Higher values (0.9-0.99) help overcome local minima and smooth oscillations.',
      },
      {
        id: 'lrDecay',
        label: 'LR Decay',
        type: 'range',
        min: 0.95,
        max: 1.0,
        step: 0.001,
        default: 0.995,
        tooltip: 'Multiplier applied to learning rate each iteration. Values < 1.0 gradually reduce the step size for fine-tuning near convergence.',
      },
      {
        id: 'useConvergence',
        label: 'Run Until Convergence',
        type: 'checkbox',
        default: true,
      },
      {
        id: 'iterations',
        label: 'Iterations',
        type: 'range',
        min: 50,
        max: 500,
        step: 10,
        default: 100,
        tooltip: 'Number of optimization steps to perform. More iterations allow the optimizer to explore further but take longer to compute.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: false,
        },
      },
      {
        id: 'maxIterations',
        label: 'Max Iterations',
        type: 'range',
        min: 500,
        max: 20000,
        step: 500,
        default: 10000,
        tooltip: 'Maximum number of iterations when using convergence mode. Acts as a safety limit to prevent infinite loops.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
      {
        id: 'convergenceThreshold',
        label: 'Convergence Threshold',
        type: 'range',
        min: 0.000001,
        max: 0.01,
        step: 0.000001,
        default: 0.0001,
        tooltip: 'Stops optimization when the gradient magnitude falls below this value, indicating we\'re near a local minimum.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
    ],
  },
  {
    id: 'adam',
    name: 'ADAM',
    color: '#ff8800',
    defaultEnabled: true,
    params: [
      {
        id: 'learningRate',
        label: 'Learning Rate',
        type: 'range',
        min: 0.001,
        max: 0.1,
        step: 0.001,
        default: 0.01,
        tooltip: 'Controls the step size at each iteration. Higher values converge faster but may overshoot; lower values are more precise but slower.',
      },
      {
        id: 'beta1',
        label: 'Beta1',
        type: 'range',
        min: 0.8,
        max: 0.999,
        step: 0.001,
        default: 0.9,
        tooltip: 'Exponential decay rate for first moment (mean). Controls the weight of recent gradients vs. history. Typical values: 0.9-0.99.',
      },
      {
        id: 'beta2',
        label: 'Beta2',
        type: 'range',
        min: 0.9,
        max: 0.9999,
        step: 0.0001,
        default: 0.999,
        tooltip: 'Exponential decay rate for second moment (variance). Controls adaptive learning rate scaling. Typical values: 0.999.',
      },
      {
        id: 'epsilon',
        label: 'Epsilon',
        type: 'range',
        min: 0.00000001,
        max: 0.0001,
        step: 0.00000001,
        default: 0.00000001,
        tooltip: 'Small constant for numerical stability. Prevents division by zero in the update rule. Typical value: 1e-8.',
      },
      {
        id: 'useConvergence',
        label: 'Run Until Convergence',
        type: 'checkbox',
        default: true,
      },
      {
        id: 'iterations',
        label: 'Iterations',
        type: 'range',
        min: 50,
        max: 500,
        step: 10,
        default: 100,
        tooltip: 'Number of optimization steps to perform. More iterations allow the optimizer to explore further but take longer to compute.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: false,
        },
      },
      {
        id: 'maxIterations',
        label: 'Max Iterations',
        type: 'range',
        min: 500,
        max: 20000,
        step: 500,
        default: 10000,
        tooltip: 'Maximum number of iterations when using convergence mode. Acts as a safety limit to prevent infinite loops.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
      {
        id: 'convergenceThreshold',
        label: 'Convergence Threshold',
        type: 'range',
        min: 0.000001,
        max: 0.01,
        step: 0.000001,
        default: 0.0001,
        tooltip: 'Stops optimization when the gradient magnitude falls below this value, indicating we\'re near a local minimum.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
    ],
  },
  {
    id: 'sgd',
    name: 'SGD (Stochastic)',
    color: '#ff4444',
    defaultEnabled: false,
    params: [
      {
        id: 'learningRate',
        label: 'Learning Rate',
        type: 'range',
        min: 0.001,
        max: 0.1,
        step: 0.001,
        default: 0.01,
        tooltip: 'Controls the step size at each iteration. Higher values converge faster but may overshoot; lower values are more precise but slower.',
      },
      {
        id: 'useConvergence',
        label: 'Run Until Convergence',
        type: 'checkbox',
        default: true,
      },
      {
        id: 'iterations',
        label: 'Iterations',
        type: 'range',
        min: 50,
        max: 500,
        step: 10,
        default: 100,
        tooltip: 'Number of optimization steps to perform. More iterations allow the optimizer to explore further but take longer to compute.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: false,
        },
      },
      {
        id: 'maxIterations',
        label: 'Max Iterations',
        type: 'range',
        min: 500,
        max: 20000,
        step: 500,
        default: 10000,
        tooltip: 'Maximum number of iterations when using convergence mode. Acts as a safety limit to prevent infinite loops.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
      {
        id: 'convergenceThreshold',
        label: 'Convergence Threshold',
        type: 'range',
        min: 0.000001,
        max: 0.01,
        step: 0.000001,
        default: 0.0001,
        tooltip: 'Stops optimization when the gradient magnitude falls below this value, indicating we\'re near a local minimum.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
    ],
  },
  {
    id: 'ballistic',
    name: 'Ballistic GD',
    color: '#ff00ff',
    defaultEnabled: true,
    params: [
      {
        id: 'dropHeight',
        label: 'Drop Height',
        type: 'range',
        min: 0.1,
        max: 50,
        step: 0.1,
        default: 5.0,
        tooltip: 'Initial height above the surface from which the ball is dropped. Higher values give the ball more initial energy.',
      },
      {
        id: 'gravity',
        label: 'Gravity',
        type: 'range',
        min: 0.1,
        max: 2,
        step: 0.1,
        default: 1.0,
        tooltip: 'Gravitational acceleration constant. Higher values make the ball fall faster and bounce more aggressively.',
      },
      {
        id: 'elasticity',
        label: 'Elasticity',
        type: 'range',
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.8,
        tooltip: 'Energy retention coefficient after each bounce (0-1). Higher values mean the ball retains more energy and bounces longer.',
      },
      {
        id: 'bounceThreshold',
        label: 'Bounce Threshold',
        type: 'range',
        min: 0.001,
        max: 0.5,
        step: 0.001,
        default: 0.05,
        tooltip: 'Minimum bounce height before stopping. When bounces become smaller than this, the ball is considered settled.',
      },
      {
        id: 'ballRadius',
        label: 'Ball Radius',
        type: 'range',
        min: 0.01,
        max: 2.0,
        step: 0.01,
        default: 0.05,
        tooltip: 'Radius of the ball. Larger radius prevents entering narrow valleys (exploration), smaller radius explores detailed features (exploitation).',
      },
      {
        id: 'maxIterations',
        label: 'Max Iterations',
        type: 'range',
        min: 500,
        max: 20000,
        step: 500,
        default: 10000,
        tooltip: 'Maximum number of simulation steps. Acts as a safety limit for the physics simulation.',
      },
    ],
  },
  {
    id: 'ballistic_adam',
    name: 'Ballistic Adam',
    color: '#00ffff',
    defaultEnabled: true,
    params: [
      {
        id: 'learningRate',
        label: 'Learning Rate',
        type: 'range',
        min: 0.001,
        max: 0.1,
        step: 0.001,
        default: 0.01,
        tooltip: 'Step size for gradient updates when on the ground. Controls how strongly gradients affect horizontal velocity.',
      },
      {
        id: 'momentum',
        label: 'Momentum',
        type: 'range',
        min: 0,
        max: 0.99,
        step: 0.01,
        default: 0.9,
        tooltip: 'Fraction of previous velocity retained each step. High values (0.9-0.99) help build speed on slopes for takeoff.',
      },
      {
        id: 'gravity',
        label: 'Gravity',
        type: 'range',
        min: 0.0001,
        max: 0.01,
        step: 0.0001,
        default: 0.001,
        tooltip: 'Gravitational acceleration for vertical motion. Controls how quickly the ball falls when airborne.',
      },
      {
        id: 'dt',
        label: 'Time Step (dt)',
        type: 'range',
        min: 0.1,
        max: 2.0,
        step: 0.1,
        default: 1.0,
        tooltip: 'Physics simulation time step. Larger values mean bigger jumps in space/time per iteration.',
      },
      {
        id: 'maxAirSteps',
        label: 'Max Air Steps',
        type: 'range',
        min: 5,
        max: 50,
        step: 1,
        default: 20,
        tooltip: 'Maximum number of physics steps to simulate while airborne before landing must be found.',
      },
      {
        id: 'maxBisectionIters',
        label: 'Max Bisection Iterations',
        type: 'range',
        min: 5,
        max: 20,
        step: 1,
        default: 10,
        tooltip: 'Maximum iterations for bisection search to find exact collision point when landing.',
      },
      {
        id: 'collisionTol',
        label: 'Collision Tolerance',
        type: 'range',
        min: 0.00001,
        max: 0.01,
        step: 0.00001,
        default: 0.001,
        tooltip: 'Accuracy threshold for collision detection. Smaller values mean more precise landing point detection.',
      },
      {
        id: 'useConvergence',
        label: 'Run Until Convergence',
        type: 'checkbox',
        default: true,
      },
      {
        id: 'iterations',
        label: 'Iterations',
        type: 'range',
        min: 50,
        max: 500,
        step: 10,
        default: 100,
        tooltip: 'Number of optimization steps to perform. Each step may involve multiple air steps if flying.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: false,
        },
      },
      {
        id: 'maxIterations',
        label: 'Max Iterations',
        type: 'range',
        min: 500,
        max: 20000,
        step: 500,
        default: 10000,
        tooltip: 'Maximum number of iterations when using convergence mode. Acts as a safety limit.',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
      {
        id: 'convergenceThreshold',
        label: 'Convergence Threshold',
        type: 'range',
        min: 0.000001,
        max: 0.01,
        step: 0.000001,
        default: 0.0001,
        tooltip: 'Stops optimization when gradient magnitude falls below this value (checked when on ground).',
        conditionalDisplay: {
          dependsOn: 'useConvergence',
          value: true,
        },
      },
    ],
  },
];
